# Resumen Intervencional: Beta=0 vs Beta óptima

Igual que en `Resumen_Observacional.ipynb`, pero sobre los 8 experimentos **Intervencional** (4 ruidos
aditivos + 4 multiplicativos): compara el modelo base (`Beta=0`) frente al modelo con la `Beta` óptima
elegida por el mismo criterio multi-métrica, y comprueba con Wilcoxon pareado si las mejoras son
significativas.

Diferencias frente al caso observacional:
- **No se incluye `HSIC(Z,Y)`**: bajo intervención, Y se fija externamente (`do(Y)`) y ya no se genera
  por su ecuación estructural, así que probar la independencia del residuo de Z frente a Y no tiene
  sentido (de hecho la columna `HSIC(Z,Y)` de estos CSVs viene vacía). Las métricas usadas son
  `MAE Z`, `HSIC(Z,X)` y `RF Acc`.
- **Nueva dimensión `Y_do`**: cada fila corresponde a `do(Y)=0.0` o `do(Y)=1.0`. Se calcula todo por
  separado para cada intervención, y además una versión "media" que agrupa ambas.
- Los 4 CSVs `multiplicativo_*` solo tienen 10 seeds (frente a 20 en `aditivo_*`), así que sus tests
  de Wilcoxon tienen menos potencia.

Todo el análisis se repite para `N=50` y `N=100`.

In [61]:
import pandas as pd
from pathlib import Path
from scipy.stats import wilcoxon

pd.set_option('display.width', 160)
pd.set_option('display.max_columns', 20)

REPO_ROOT = Path.cwd().parents[0] if Path.cwd().name == "notebooks" else Path.cwd()
NOTEBOOKS_DIR = REPO_ROOT / "notebooks"

ALPHA = 0.05
METRICAS = ["MAE Z", "HSIC(Z,X)", "RF Acc"]  # menor es mejor en las 3; sin HSIC(Z,Y) (no aplica bajo do(Y))

## Definición de los 8 experimentos intervencionales

In [62]:
EXPERIMENTOS = {
    "Aditivo Gaussiano": NOTEBOOKS_DIR / "Experimento1/Intervencional-20/tablas/intervencional_aditivo_gausian.csv",
    "Aditivo Exponencial": NOTEBOOKS_DIR / "Experimento1/Intervencional-20/tablas/intervencional_aditivo_exponencial.csv",
    "Aditivo Gamma": NOTEBOOKS_DIR / "Experimento1/Intervencional-20/tablas/intervencional_aditivo_gamma.csv",
    "Aditivo Uniforme": NOTEBOOKS_DIR / "Experimento1/Intervencional-20/tablas/intervencional_aditivo_uniforme.csv",
    "Multiplicativo Gaussiano": NOTEBOOKS_DIR / "Experimento2/Intervencional/tablas/intervencional_multiplicativo_gausian.csv",
    "Multiplicativo Exponencial": NOTEBOOKS_DIR / "Experimento2/Intervencional/tablas/intervencional_multiplicativo_exponencial.csv",
    "Multiplicativo Gamma": NOTEBOOKS_DIR / "Experimento2/Intervencional/tablas/intervencional_multiplicativo_gamma.csv",
    "Multiplicativo Uniforme": NOTEBOOKS_DIR / "Experimento2/Intervencional/tablas/intervencional_multiplicativo_uniforme.csv",
}

for nombre, path in EXPERIMENTOS.items():
    assert path.exists(), f"No existe: {path}"

## Función de selección de la Beta óptima

In [63]:
def beta_optima(df: pd.DataFrame, n_filter: int, y_do_filter, metrics=METRICAS):
    """Selecciona la Beta óptima (Beta != 0) de un experimento según un criterio multi-métrica.

    Beta=0 se usa solo como referencia (baseline) y nunca puede ser el resultado.
    `y_do_filter`: 0.0 o 1.0 para quedarse con esa intervención, o None para agrupar ambas (media).

    1) Filtra N == n_filter (y Y_do == y_do_filter si no es None), promedia cada métrica por Beta
       (sobre las seeds -y, si aplica, ambos Y_do- disponibles) y descarta Beta=0 de las candidatas.
    2) Para cada métrica, halla la Beta > 0 que minimiza su media -> betas candidatas.
    3) Para cada beta candidata, cuenta cuántas métricas mejoran/empeoran frente a Beta=0 y calcula
       la mejora relativa (%) de cada métrica frente al baseline.
    4) Se ordenan las candidatas por: (a) menos métricas empeoradas, (b) más métricas mejoradas,
       (c) mayor mejora relativa total, (d) último desempate (solo si empatan exactamente):
       mayor mejora relativa en una única métrica. Se elige la primera.

    Devuelve (baseline, beta_opt, valores_opt, candidatas, criterio).
    """
    df_n = df[df["N"] == n_filter]
    if y_do_filter is not None:
        df_n = df_n[df_n["Y_do"] == y_do_filter]

    media_por_beta = df_n.groupby("Beta")[list(metrics)].mean()

    baseline = media_por_beta.loc[0.0]
    media_no_cero = media_por_beta.drop(index=0.0)

    betas_candidatas = sorted(set(media_no_cero[m].idxmin() for m in metrics))

    filas_candidatas = []
    for beta in betas_candidatas:
        valores = media_no_cero.loc[beta]
        mejora_relativa = (baseline - valores) / baseline
        filas_candidatas.append({
            "Beta": beta,
            "n_mejoradas": int((valores < baseline).sum()),
            "n_empeoradas": int((valores > baseline).sum()),
            "mejora_relativa_total": float(mejora_relativa.sum()),
            "mejora_relativa_max": float(mejora_relativa.max()),
        })

    candidatas = pd.DataFrame(filas_candidatas).sort_values(
        by=["n_empeoradas", "n_mejoradas", "mejora_relativa_total", "mejora_relativa_max"],
        ascending=[True, False, False, False],
    ).reset_index(drop=True)

    ganadora = candidatas.iloc[0]
    beta_opt = float(ganadora["Beta"])
    valores_opt = media_por_beta.loc[beta_opt]

    if ganadora["n_empeoradas"] == 0:
        criterio = "domina al baseline (mejora >=1 metrica sin empeorar ninguna)"
    else:
        criterio = "mejor compromiso (ninguna beta evita empeorar alguna metrica)"

    return baseline, beta_opt, valores_opt, candidatas, criterio

## Función de test de Wilcoxon pareado

Se empareja por `(Seed, Y_do)` en vez de solo `Seed`: así funciona igual si se filtra a un único
`Y_do` (queda un valor de `Y_do` por seed, como antes) o si se agrupan ambos (quedan 2 filas por seed,
una por intervención, cada una emparejada con su contraparte en la misma condición).

In [64]:
def wilcoxon_experimento(df: pd.DataFrame, beta_opt: float, n_filter: int, y_do_filter, metrics=METRICAS):
    """Wilcoxon signed-rank pareado entre Beta=0 y Beta=beta_opt, por métrica.

    H0: no hay diferencia. H1 (alternative='less'): el valor en beta_opt es menor (mejor) que en Beta=0.
    Devuelve (p_valores: dict metrica->p, n_pares: int).
    """
    df_n = df[df["N"] == n_filter]
    if y_do_filter is not None:
        df_n = df_n[df_n["Y_do"] == y_do_filter]

    base = df_n[df_n["Beta"] == 0.0].set_index(["Seed", "Y_do"])[list(metrics)]
    opt = df_n[df_n["Beta"] == beta_opt].set_index(["Seed", "Y_do"])[list(metrics)]
    pares_comunes = sorted(set(base.index) & set(opt.index))
    base = base.loc[pares_comunes]
    opt = opt.loc[pares_comunes]

    p_valores = {}
    for m in metrics:
        try:
            _, p = wilcoxon(opt[m].values, base[m].values, alternative="less")
        except ValueError:
            p = float("nan")
        p_valores[m] = p
    return p_valores, len(pares_comunes)

## Cálculo (tabla resumen + p-valores) para un (N, do(Y)) dado

In [65]:
def analizar(n_filter: int, y_do_filter):
    """Ejecuta beta_optima + wilcoxon_experimento para los 8 experimentos, a N y Y_do fijos.

    y_do_filter: 0.0, 1.0, o None (media entre ambas intervenciones).
    Devuelve (resumen: DataFrame, p_values: DataFrame, diagnostico: dict[str, DataFrame]).
    """
    filas_resumen = []
    filas_p = []
    diagnostico = {}

    for nombre, path in EXPERIMENTOS.items():
        df = pd.read_csv(path)
        baseline, beta_opt, valores_opt, candidatas, criterio = beta_optima(df, n_filter, y_do_filter)
        diagnostico[nombre] = candidatas

        filas_resumen.append({
            "Experimento": nombre,
            "beta_optima": beta_opt,
            "MAE(Z) beta=0": baseline["MAE Z"],
            "MAE(Z) beta_optima": valores_opt["MAE Z"],
            "HSIC(Z,X) beta=0": baseline["HSIC(Z,X)"],
            "HSIC(Z,X) beta_optima": valores_opt["HSIC(Z,X)"],
            "RF Acc beta=0": baseline["RF Acc"],
            "RF Acc beta_optima": valores_opt["RF Acc"],
            "Criterio": criterio,
        })

        p_valores, n_pares = wilcoxon_experimento(df, beta_opt, n_filter, y_do_filter)
        filas_p.append({"Experimento": nombre, **p_valores, "n_pares": n_pares})

    resumen = pd.DataFrame(filas_resumen)
    p_values = pd.DataFrame(filas_p).set_index("Experimento")
    return resumen, p_values, diagnostico


resultados = {}
for n_filter in (50, 100):
    for y_do_filter, etiqueta in ((0.0, "ydo0"), (1.0, "ydo1"), (None, "media")):
        resultados[(n_filter, etiqueta)] = analizar(n_filter, y_do_filter)

## Funciones de formato y resaltado en negrita

In [66]:
COLUMNA_A_METRICA = {
    "MAE(Z) beta_optima": "MAE Z",
    "HSIC(Z,X) beta_optima": "HSIC(Z,X)",
    "RF Acc beta_optima": "RF Acc",
}


def formatear(resumen: pd.DataFrame):
    cols_num = [c for c in resumen.columns if c not in ("Experimento", "beta_optima", "Criterio")]
    fmt = resumen.copy()
    fmt[cols_num] = fmt[cols_num].round(5)
    fmt["beta_optima"] = fmt["beta_optima"].round(2)
    return fmt


def tabla_con_negrita(resumen: pd.DataFrame, p_values: pd.DataFrame):
    """Tabla resumen con las celdas 'beta_optima' en negrita cuando su p-valor (Wilcoxon) < ALPHA.

    Solo aplica en la visualización del notebook (un CSV plano no admite negrita).
    """
    fmt = formatear(resumen)

    def resaltar(row):
        p_exp = p_values.loc[row["Experimento"]]
        estilos = []
        for col in row.index:
            metrica = COLUMNA_A_METRICA.get(col)
            if metrica is not None and pd.notna(p_exp[metrica]) and p_exp[metrica] < ALPHA:
                estilos.append("font-weight: bold")
            else:
                estilos.append("")
        return estilos

    return fmt.style.apply(resaltar, axis=1)

## N = 50

### do(Y) = 0.0

In [67]:
resumen, p_values = resultados[(50, "ydo0")][0], resultados[(50, "ydo0")][1]
tabla_con_negrita(resumen, p_values)

In [68]:
p_values.round(4)

                             MAE Z  HSIC(Z,X)  RF Acc  n_pares
Experimento
Aditivo Gaussiano           0.4062     0.0527  0.0006       20
Aditivo Exponencial         0.1227     0.1559  0.2806       20
Aditivo Gamma               0.0825     0.0947  0.0766       20
Aditivo Uniforme            0.1567     0.0181  0.1189       20
Multiplicativo Gaussiano    0.1377     0.0967  0.1328       10
Multiplicativo Exponencial  0.1377     0.0029  0.2969       10
Multiplicativo Gamma        0.0322     0.1377  0.0039       10
Multiplicativo Uniforme     0.0420     0.0244  0.9453       10

### do(Y) = 1.0

In [69]:
resumen, p_values = resultados[(50, "ydo1")][0], resultados[(50, "ydo1")][1]
tabla_con_negrita(resumen, p_values)

In [70]:
p_values.round(4)

                             MAE Z  HSIC(Z,X)  RF Acc  n_pares
Experimento
Aditivo Gaussiano           0.3238     0.0107  0.0242       20
Aditivo Exponencial         0.7271     0.0148  0.5475       20
Aditivo Gamma               0.2105     0.0014  0.8455       20
Aditivo Uniforme            0.4347     0.0615  0.6913       20
Multiplicativo Gaussiano    0.0029     0.0020  0.2637       10
Multiplicativo Exponencial  0.0020     0.0322  0.1523       10
Multiplicativo Gamma        0.0322     0.0322  0.0664       10
Multiplicativo Uniforme     0.3477     0.1162  0.3750       10

### Media entre do(Y)=0.0 y do(Y)=1.0

In [71]:
resumen, p_values = resultados[(50, "media")][0], resultados[(50, "media")][1]
tabla_con_negrita(resumen, p_values)

In [72]:
p_values.round(4)

                             MAE Z  HSIC(Z,X)  RF Acc  n_pares
Experimento
Aditivo Gaussiano           0.1505     0.0218  0.0386       40
Aditivo Exponencial         0.2025     0.0104  0.4459       40
Aditivo Gamma               0.3673     0.0108  0.2400       40
Aditivo Uniforme            0.2340     0.0265  0.5819       40
Multiplicativo Gaussiano    0.2045     0.0242  0.2763       20
Multiplicativo Exponencial  0.2262     0.0000  0.0528       20
Multiplicativo Gamma        0.0086     0.0164  0.0044       20
Multiplicativo Uniforme     0.0487     0.1012  0.5208       20

## N = 100

### do(Y) = 0.0

In [73]:
resumen, p_values = resultados[(100, "ydo0")][0], resultados[(100, "ydo0")][1]
tabla_con_negrita(resumen, p_values)

In [74]:
p_values.round(4)

                             MAE Z  HSIC(Z,X)  RF Acc  n_pares
Experimento
Aditivo Gaussiano           0.1942     0.1227  0.6732       20
Aditivo Exponencial         0.0010     0.0002  0.2791       20
Aditivo Gamma               0.0884     0.0220  0.7087       20
Aditivo Uniforme            0.2045     0.0825  0.2384       20
Multiplicativo Gaussiano    0.2461     0.0654  0.1172       10
Multiplicativo Exponencial  0.0098     0.0186  0.4375       10
Multiplicativo Gamma        0.0244     0.1611  0.4492       10
Multiplicativo Uniforme     0.5000     0.5000  0.5391       10

### do(Y) = 1.0

In [75]:
resumen, p_values = resultados[(100, "ydo1")][0], resultados[(100, "ydo1")][1]
tabla_con_negrita(resumen, p_values)

In [76]:
p_values.round(4)

                             MAE Z  HSIC(Z,X)  RF Acc  n_pares
Experimento
Aditivo Gaussiano           0.7392     0.4062  0.0918       20
Aditivo Exponencial         0.1305     0.0000  0.9178       20
Aditivo Gamma               0.9552     0.0120  0.8324       20
Aditivo Uniforme            0.2979     0.2729  0.0844       20
Multiplicativo Gaussiano    0.6523     0.5771  0.4727       10
Multiplicativo Exponencial  0.0967     0.0068  0.4219       10
Multiplicativo Gamma        0.0801     0.0654  0.1211       10
Multiplicativo Uniforme     0.9678     0.9346  0.4395       10

### Media entre do(Y)=0.0 y do(Y)=1.0

In [77]:
resumen, p_values = resultados[(100, "media")][0], resultados[(100, "media")][1]
tabla_con_negrita(resumen, p_values)

In [78]:
p_values.round(4)

                             MAE Z  HSIC(Z,X)  RF Acc  n_pares
Experimento
Aditivo Gaussiano           0.4393     0.1569  0.2921       40
Aditivo Exponencial         0.0011     0.0000  0.6536       40
Aditivo Gamma               0.4973     0.0025  0.7841       40
Aditivo Uniforme            0.1474     0.0750  0.0483       40
Multiplicativo Gaussiano    0.3371     0.1942  0.2200       20
Multiplicativo Exponencial  0.0018     0.0002  0.2646       20
Multiplicativo Gamma        0.0053     0.0242  0.0769       20
Multiplicativo Uniforme     0.3238     0.4062  0.2490       20

## Comparación entre las 6 combinaciones (N x do(Y))

Beta óptima elegida y número de métricas significativas (de 3: `MAE Z`, `HSIC(Z,X)`, `RF Acc`) en
cada combinación, para ver de un vistazo qué cambia con N y con la intervención.

In [79]:
combos = [(50, "ydo0"), (50, "ydo1"), (50, "media"), (100, "ydo0"), (100, "ydo1"), (100, "media")]

comparacion = pd.DataFrame({"Experimento": list(EXPERIMENTOS.keys())})
for n_filter, etiqueta in combos:
    resumen_c, p_values_c, _ = resultados[(n_filter, etiqueta)]
    col_beta = f"beta_optima N={n_filter} {etiqueta}"
    col_sig = f"metricas_sig N={n_filter} {etiqueta}"
    comparacion = comparacion.merge(
        resumen_c[["Experimento", "beta_optima"]].rename(columns={"beta_optima": col_beta}),
        on="Experimento",
    )
    comparacion[col_sig] = comparacion["Experimento"].map((p_values_c[METRICAS] < ALPHA).sum(axis=1))

comparacion

,Experimento,beta_optima N=50 ydo0,metricas_sig N=50 ydo0,beta_optima N=50 ydo1,metricas_sig N=50 ydo1,beta_optima N=50 media,metricas_sig N=50 media,beta_optima N=100 ydo0,metricas_sig N=100 ydo0,beta_optima N=100 ydo1,metricas_sig N=100 ydo1,beta_optima N=100 media,metricas_sig N=100 media
0,Aditivo Gaussiano,0.1,1,0.5,2,0.4,2,0.2,0,0.2,0,0.2,0
1,Aditivo Exponencial,0.1,0,0.1,1,0.1,1,0.3,2,0.3,1,0.3,2
2,Aditivo Gamma,0.3,0,0.1,1,0.3,1,0.1,1,0.3,1,0.1,1
3,Aditivo Uniforme,0.1,1,0.4,0,0.2,1,0.1,0,0.1,0,0.1,1
4,Multiplicativo Gaussiano,0.9,0,0.7,2,0.9,1,0.2,0,0.2,0,0.2,0
5,Multiplicativo Exponencial,0.9,1,0.4,2,0.9,1,0.5,2,0.2,1,0.4,2
6,Multiplicativo Gamma,0.6,2,0.7,2,0.7,3,0.6,1,0.7,0,0.7,2
7,Multiplicativo Uniforme,0.5,2,0.1,0,0.5,1,0.4,0,0.8,0,0.2,0

## Guardar CSVs resumen

In [80]:
for (n_filter, etiqueta), (resumen_c, _, _) in resultados.items():
    out_path = NOTEBOOKS_DIR / "tablas" / f"resumen_intervencional_beta_n{n_filter}_{etiqueta}.csv"
    resumen_c.to_csv(out_path, index=False)
    print(f"Guardado en: {out_path}")

Guardado en: /Users/clau/Documents/TFM_NUEVO/CODIGO_COMPLETO/kacgm-hsic/kacgm_hsic/notebooks/tablas/resumen_intervencional_beta_n50_ydo0.csv
Guardado en: /Users/clau/Documents/TFM_NUEVO/CODIGO_COMPLETO/kacgm-hsic/kacgm_hsic/notebooks/tablas/resumen_intervencional_beta_n50_ydo1.csv
Guardado en: /Users/clau/Documents/TFM_NUEVO/CODIGO_COMPLETO/kacgm-hsic/kacgm_hsic/notebooks/tablas/resumen_intervencional_beta_n50_media.csv
Guardado en: /Users/clau/Documents/TFM_NUEVO/CODIGO_COMPLETO/kacgm-hsic/kacgm_hsic/notebooks/tablas/resumen_intervencional_beta_n100_ydo0.csv
Guardado en: /Users/clau/Documents/TFM_NUEVO/CODIGO_COMPLETO/kacgm-hsic/kacgm_hsic/notebooks/tablas/resumen_intervencional_beta_n100_ydo1.csv
Guardado en: /Users/clau/Documents/TFM_NUEVO/CODIGO_COMPLETO/kacgm-hsic/kacgm_hsic/notebooks/tablas/resumen_intervencional_beta_n100_media.csv